site:
  title: Hybrid Fraud Detection on Intel Xeon
  url: https://github.com/jkershawrh/hybrid-fraud-detection
  start_page: hybrid-fraud-detection::index.adoc

content:
  sources:
    - url: .
      start_path: showroom

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true
  supplemental_files: ./showroom/supplemental-ui

asciidoc:
  attributes:
    showroom-collection-version: v1.6.8

output:
  dir: ./www
