apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-scorer
  labels:
    app.kubernetes.io/name: hybrid-fraud-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-scorer
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
