apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-scorer
  labels:
    app.kubernetes.io/name: hybrid-fraud-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hybrid-fraud-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
