FROM registry.access.redhat.com/ubi9/python-311@sha256:a0bdb55576fc5b8d6704279307817828ef027e1065533ceba133fe9516003a6c

WORKDIR /opt/app-root/src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scorer.py .
COPY ui.py .

EXPOSE 8000

CMD ["uvicorn", "scorer:app", "--host", "0.0.0.0", "--port", "8000"]
